### ISSUE TITLE
wtKst crashes when called using mono

### ISSUE THREAD

**Issue by dh1aky** [dl8aau/wtkst#4]
Both AirScout and wtKst written in C#, so the only way to get that running under Linux is using mono.
AirScout runs fine using mono, Win-Test also.

The only component doesn't run using mono is the small wtKst now. So I have to install that bloatware-full Windows on all my devices.

So please give it a chance running on Linux

**Comment by Rsclub22** [comment]
works on Archlinux with wine version wine-9.8 and wtKST v3.1.4.11

**Comment by dh1aky** [comment]
It crashed because of missing some fonts.
Go to winehq and download the latest stable wine emulator. The fonts now included.

**Comment by dh1aky** [comment]
works now.

**Comment by dh1aky** [comment]
Works using the latest winehq release from dev branch
