### ISSUE TITLE
feature req: 50/70MHz support

### ISSUE THREAD

**Issue by lowiess** [dl8aau/wtkst#5]
Could please also add the 50/70 Mhz in the options for calls ?

**Comment by dl8aau** [comment]
needs to be added to the UI. Note that the Airscout database does not have entries for 50/70 yet.

**Comment by dl8aau** [comment]
added to a branch band50_70
Airscout database does have entries for 50/70MHz, although not too many

**Comment by dl8aau** [comment]
closed in f4c91e590

**Comment by dl8aau** [comment]
Closed in f4c91e590
